### ISSUE TITLE
installing lunaR on mac

### ISSUE THREAD

**Issue by y-yyang** [remnrem/luna#13] opened 2024-09-30 10:25 UTC
hello, I'm getting the following error during installation:

g++ -O2 -std=gnu++17 -MMD -MP -I. -I.. -Wno-psabi -Wno-unused-result  -I/Users/k2477128/fftw//include -I/usr/local/include -fPIC -I/opt/R/arm64/include  -c -o dynamics/e-cycles.o dynamics/e-cycles.cpp
dynamics/e-cycles.cpp:38:1: error: use of undeclared identifier 'ecycles_t'; did you mean 'caches_t'?
ecycles_t::ecycles_t( edf_t & edf , param_t & param )
^~~~~~~~~
caches_t
./timeline/cache.h:226:8: note: 'caches_t' declared here
struct caches_t {
       ^
dynamics/e-cycles.cpp:38:12: error: a type specifier is required for all declarations
ecycles_t::ecycles_t( edf_t & edf , param_t & param )
           ^
2 errors generated.
make: *** [dynamics/e-cycles.o] Error 1
make: *** Waiting for unfinished jobs....
cp: *.a: No such file or directory

**Comment by RebeccaAHayes** [comment] 2024-10-15 17:56
I am also getting this installation error on a Linux machine.

**Comment by remnrem** [comment] 2024-11-18 21:49
this was a temporary issue caused by an intermediate version of the luna base library being posted, is fixed now.

**Closed** 2024-11-18 21:49 UTC
